jenkins-master2:
  container_name: custom_j2_master
  image: jenkins-custom-master 
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
    JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
